// Generated by CoffeeScript 1.5.0

chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
  if (request.greeting === "getDom") {
    return sendResponse({
      title: document.title,
      content: document.documentElement.outerHTML
    });
  } else {
    return sendResponse({});
  }
});
