// Generated by CoffeeScript 1.5.0
var getImage;

chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
  if (request.greeting === "getDom") {
    return sendResponse({
      title: document.title,
      content: document.documentElement.outerHTML
    });
  } else if (request.greeting === "getBackgroundImage") {
    return sendResponse({
      image_url: getImage()
    });
  } else {
    return sendResponse({});
  }
});

getImage = function() {
  var style;
  style = document.body.currentStyle || window.getComputedStyle(document.body, false);
  return style.backgroundImage.slice(4, -1);
};
