// Generated by CoffeeScript 1.5.0
var autoSave, copy, defaultTitle, editor, editorSession, getMimeType, goHome, main, mbo, preview, quickNoteDir, recovery, save, saveBackgroundImage, updateStatusBar;

goHome = function() {
  return chrome.tabs.create({
    url: chrome.extension.getURL("index.html")
  });
};

mbo = chrome.extension.getBackgroundPage();

editor = "";

editorSession = "";

quickNoteDir = "/quickNotes";

defaultTitle = "UNTITLED.md";

copy = function() {
  var title;
  title = document.getElementById("title");
  return chrome.tabs.getSelected(null, function(tab) {
    return chrome.tabs.sendMessage(tab.id, {
      greeting: "getDom"
    }, function(response) {
      title.value = sprintf("%s.html", response.title);
      return editorSession.setValue(response.content);
    });
  });
};

autoSave = function() {
  var path, title;
  title = document.getElementById("title");
  if (!title.value) {
    title.value = defaultTitle;
  }
  if (mbo.core().valid) {
    path = sprintf("%s%s/%s", mbo.core().sourceDir, quickNoteDir, title.value);
    return mbo.core().saveNote(path, editorSession.getValue());
  } else {
    return mbo.notify("daemon failed. Please restart");
  }
};

preview = function() {
  var notification, url;
  url = sprintf("notification.html#%s", escape(editorSession.getValue()));
  notification = webkitNotifications.createHTMLNotification(url);
  return notification.show();
};

save = function() {
  var title;
  autoSave();
  title = document.getElementById("title");
  mbo.current_file = sprintf("%s/%s", quickNoteDir, title.value);
  mbo.notify(sprintf("saved: %s", title.value));
  return window.close();
};

saveBackgroundImage = function() {
  var title;
  title = document.getElementById("title");
  return chrome.tabs.getSelected(null, function(tab) {
    return chrome.tabs.sendMessage(tab.id, {
      greeting: "getBackgroundImage"
    }, function(response) {
      console.log(response);
      title.value = response.image_url;
      return chrome.tabs.create({
        url: response.image_url
      });
    });
  });
};

recovery = function(title) {
  var path;
  path = sprintf("%s/%s", quickNoteDir, title);
  return editorSession.setValue(mbo.core().getContent(path));
};

main = function() {
  var title;
  editor = ace.edit("editor");
  editor.setTheme("ace/theme/github");
  editor.renderer.setShowGutter(false);
  editorSession = editor.getSession();
  editorSession.setMode("ace/mode/markdown");
  recovery(defaultTitle);
  editorSession.on('change', function() {
    return autoSave();
  });
  title = document.getElementById("title");
  return title.oninput = function() {
    var extension;
    extension = title.value.split(".").pop();
    editorSession.setMode(sprintf("ace/mode/%s", getMimeType(extension)));
    return updateStatusBar(sprintf("%s/%s", quickNoteDir, title.value));
  };
};

updateStatusBar = function(t) {
  var file_path, msg, url;
  url = sprintf("http://localhost:3600%s.html", t);
  file_path = sprintf("~/.marboo/source%s", t);
  msg = sprintf("<a href=\"%s\">%s</a>", url, t);
  return document.getElementById("statusBar").innerHTML = msg;
};

getMimeType = function(extension) {
  if (extension === "js") {
    return "javascript";
  } else if (extension === "txt") {
    return "text";
  } else if (extension === "htm") {
    return "html";
  } else if (extension === "md") {
    return "markdown";
  } else if (extension === "rb") {
    return "ruby";
  } else if (extension === "py") {
    return "python";
  } else if (extension === "c" || extension === "cpp") {
    return "c_cpp";
  } else {
    return extension;
  }
};

document.addEventListener('DOMContentLoaded', function() {
  document.getElementById("title").focus();
  document.getElementById('main').addEventListener('click', goHome);
  document.getElementById('copyButton').addEventListener('click', copy);
  document.getElementById('saveButton').addEventListener('click', save);
  document.getElementById('saveBgImage').addEventListener('click', saveBackgroundImage);
  return main();
});
